#! /bin/bash
# Developer & Maintainer: Juan Rodenas
# Title: honeypot log
# Description: Send the log to Telegram every few days
# Created: 20.09.2022 11:39

# requeriments:
TOKEN="YOUR_TOKEN_BOT"
ID="YOUR_TOKEN_CHAT"
URL="https://api.telegram.org/bot$TOKEN/sendMessage"
DNS="1.1.1.1"
log=$(cat /var/log/messages | grep -i "WAN_IN-10-D" | awk -F "=" '{print $5}' | awk '{print $1}' | sort | uniq -c)

# Envío del mensaje
/usr/bin/ping -c2 $DNS > /dev/null 2>&1
if [ $? -ne 0 ]
then
        exit 0
else
        curl -s -X POST $URL \
        -d chat_id=$ID \
        -d parse_mode=HTML \
        -d text="$(printf "$MSG\n\t\t- LOG: <code>$mensaje</code>")" \
                > /dev/null 2>&1
        exit 0
fi